### ISSUE TITLE
wrong height.

### ISSUE THREAD

**Issue by yetzt** [ReneHollander/node-canvas#1]
i tried your code on a raspberry pi with a 4k display. works so far, but the canvas seems to have the wrong size:

```
Width: 3840, Height: 3840
```

**Comment by ReneHollander** [comment]
Which functions do you use to read the width and height in node? Does it actually work or is it just returning the wrong values?

**Comment by yetzt** [comment]
it's what the example script says:

```
console.log("Width: " + canvas.width + ", Height: " + canvas.height);
```

i did no thorough testing so far. the sample script crashes on `canvas.createPNGStream();`, but i managed to write a simple test script which [works fine so far](https://dl.dropboxusercontent.com/u/6232/IMG_6018.MOV).

**Comment by ReneHollander** [comment]
I will look into the height issue. Instead of `canvas.createPNGStream();` you can use `toBuffer()` and write the result into a file with the fs module. The exported file should be a png.

**Comment by ReneHollander** [comment]
Can you maybe check the output of `fbset --show`? You need install the `fbset` package for the command to work.

**Comment by yetzt** [comment]
```
root@weywot:~# fbset --show --info

mode "3840x2160"
    geometry 3840 2160 3840 2160 16
    timings 0 0 0 0 0 0 0
    rgba 5/11,6/5,5/0,0/16
endmode

Frame buffer device information:
    Name        : BCM2708 FB
    Address     : 0x3cc28000
    Size        : 16588800
    Type        : PACKED PIXELS
    Visual      : TRUECOLOR
    XPanStep    : 1
    YPanStep    : 1
    YWrapStep   : 0
    LineLength  : 7680
    Accelerator : No
```

**Comment by piranna** [comment]
I've fixed height at https://github.com/Automattic/node-canvas/pull/571

**Comment by yetzt** [comment]
:+1:
